- id: update_morning_commute_sensor
  alias: Commute - Update morning commute sensor
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: "06:00:00"
    before: "11:00:00"
  - condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.work_by_car
  mode: restart

- id: arrive_home
  alias: "Arrive Home"
  trigger:
    - platform: state
      entity_id:
        - person.dale
      to: home
  action:
    service: notify.mobile_app_dales_iphone_xs
    data:
      message: "Welcome home"

- id: sunset
  alias: "Turn on lights at dusk"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5
  action:
    service: scene.turn_on
    entity_id: scene.evening

- id: loadshedding_update_home_schedule
  alias: "Update loadshedding schedule"
  trigger:
    platform: mqtt
    topic: "loadshedding/home/next"
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.loadshedding_home_next
    data:
      datetime: "{{ trigger.payload_json.next }}"

- id: loadshedding_warning
  alias: "Loadshedding 15 min warning"
  trigger:
    platform: template
    value_template: "{{ ((as_timestamp(states('sensor.date_time').replace(',', '')) | int) + 15*60) == (state_attr('input_datetime.loadshedding_home_next', 'timestamp') | int)  }}"
  action:
    service: notify.mobile_app_dales_iphone_xs
    data:
      message: "Loadshedding in 15 min"

