- id: update_morning_commute_sensor
  alias: Commute - Update morning commute sensor
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: "06:00:00"
    before: "11:00:00"
  - condition: state
    entity_id: "binary_sensor.workday_sensor"
    state: "on"
  action:
  - service: homeassistant.update_entity
    entity_id: sensor.work_by_car
  mode: restart

- id: arrive_home
  alias: "Arrive Home"
  trigger:
    - platform: state
      entity_id:
        - person.dale
      to: home
  action:
    service: notify.mobile_app_dales_iphone_xs
    data:
      message: "Welcome home"

- id: sunset
  alias: "Turn on lights at dusk"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5
  action:
    service: scene.turn_on
    entity_id: scene.evening
