- platform: climate_group
  name: "All thermostats"
  entities:
    - climate.lounge_west_thermostat
    - climate.lounge_north_thermostat
    - climate.lounge_east_thermostat
    - climate.study_thermostat
    - climate.bedroom_thermostat

- platform: climate_group
  name: "Lounge thermostat"
  entities:
    - climate.lounge_west_thermostat
    - climate.lounge_north_thermostat
    - climate.lounge_east_thermostat
