- platform: generic_thermostat
  name: Study
  heater: switch.fanheater
  target_sensor: sensor.study_temperature
  min_temp: 15
  max_temp: 25
  target_temp: 20
  min_cycle_duration:
    seconds: 5
  away_temp: 15
  precision: 0.5
