homeassistant:
  name: Home
  time_zone: Europe/Stockholm
  unit_system: metric
  temperature_unit: C
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  country: SE
  internal_url: !secret internal_url
  external_url: !secret external_url
  auth_providers:
  - type: homeassistant
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.1.0/24  # Proxy network range
  ip_ban_enabled: true
  login_attempts_threshold: 5

person:

notify:
  - platform: group
    name: family
    services:
      - service: mobile_app_dales_iphone
      - service: mobile_app_fruutish

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 75
    icon: mdi:briefcase

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    scan_interval: 3600  # Default is 5s, but I don't need a live view
    draw: ['all']
    attributes:
      - calibration_points
    map_transformation:
      rotate: 0
      trim:
        top: 0
        bottom: 0
        left: 0
        right: 0

input_datetime:
  laundry_reminder:
    name: Laundry reminder
    has_date: true
    has_time: true
  easy_wakeup:
    name: Easy wakeup
    has_time: true
  dale_alarm_time:
    name: Dale's alarm time
    has_time: true

input_number:
  illuminance_lower:
    name: Illuminance lower
    min: 0
    max: 200
    step: 1
    unit_of_measurement: lx
  illuminance_upper:
    name: Illuminance upper
    min: 0
    max: 200
    step: 1
    unit_of_measurement: lx

input_boolean:
  run_vacuum_today:
    name: Run vacuum today
    icon: mdi:robot-vacuum
  dale_alarm_enable:
    name: Dale's alarm enabled


counter:
  empty_vacuum_bin:
    name: Empty vacuum bin
    initial: 2
    icon: mdi:delete-variant

frontend:

mobile_app:

ios:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include HASSGoogAssist.json
  report_state: true
  exposed_domains:
    - climate
    - light
    - scene
    - script
  entity_config:
    light.vindriktning_status:
      expose: false

homekit:

media_source: 

media_player:

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

tts:
  - platform: google_cloud
    key_file: HASSGoogAssist.json
    voice: en-GB-Wavenet-B
    profiles:
      - large-home-entertainment-class-device
  - platform: marytts
    host: home_mimic3
    voice: en_US/ljspeech_low
    language: en_US

system_health:

history:

sun:

logbook:

logger:
  logs:
    pyatv: debug
    homeassistant.components.apple_tv: debug
    custom_components.xiaomi_cloud_map_extractor: debug

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml  # legacy. Rather use template.yaml
climate: !include climate.yaml
light: !include lights.yaml
mqtt: !include mqtt.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml  # legacy. Rather use template.yaml
switch: !include switch.yaml
template: !include template.yaml
timer: !include timer.yaml
