homeassistant:
  name: Home
  time_zone: Europe/Stockholm
  unit_system: metric
  temperature_unit: C
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  internal_url: !secret homeassistant_url
  external_url: !secret homeassistant_url
  auth_providers:
  - type: homeassistant
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.1.0/24  # Proxy network range
  ip_ban_enabled: true
  login_attempts_threshold: 5

person:

notify:
  - platform: group
    name: family
    services:
      - service: mobile_app_dales_iphone
      - service: mobile_app_fruutish

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 75
    icon: mdi:briefcase

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  discovery: true
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

camera:

input_datetime:

input_number:
  rssi_present:
    name: RSSI present threshold
    initial: -77
    min: -100
    max: -40
    step: 1
    unit_of_measurement: dBm
  rssi_not_present:
    name: RSSI not-present threshold
    initial: -90
    min: -100
    max: -40
    step: 1
    unit_of_measurement: dBm

frontend:

mobile_app:

discovery:

ios:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include HASSGoogAssist.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

homekit:

apple_tv:

tts:
  - platform: google_cloud
    key_file: HASSGoogAssist.json
    voice: en-GB-Wavenet-B
    profiles:
      - large-home-entertainment-class-device
    base_url: !secret tts_base_url

updater:

system_health:

history:

sun:

logbook:

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
group: !include groups.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
timer: !include timer.yaml
template: !include template.yaml
