homeassistant:
  name: Home
  time_zone: Africa/Johannesburg
  unit_system: metric
  temperature_unit: C
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  internal_url: !secret homeassistant_url
  external_url: !secret homeassistant_url
  auth_providers:
  - type: homeassistant
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.1.0/24  # Proxy network range
  ip_ban_enabled: true
  login_attempts_threshold: 5

person:

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 1000
    icon: mdi:briefcase

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  discovery: true
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

camera:
  - platform: mqtt
    topic: weathersa/ct50.gif
    name: Cape Town 50km radar
    unique_id: ct50radar
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points
    map_transformation:
      rotate: 0
      trim:
        top: 20
        bottom: 20
        left: 20
        right: 20


input_datetime:
  loadshedding_home_next:
    name: Next scheduled loadshed time
    has_date: true
    has_time: true

frontend:

mobile_app:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include HASSGoogAssist.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

homekit:

apple_tv:

tts:
  - platform: google_cloud
    key_file: HASSGoogAssist.json
    voice: en-GB-Wavenet-B
    profiles:
      - large-home-entertainment-class-device
    base_url: !secret tts_base_url

updater:

system_health:

history:

sun:

logbook:

sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
automation: !include automations.yaml
group: !include groups.yaml
light: !include lights.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml
template: !include template.yaml
