# Load default config
#default_config:

homeassistant:
  name: Home
  time_zone: Africa/Johannesburg
  unit_system: metric
  temperature_unit: C
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  internal_url: !secret homeassistant_url
  external_url: !secret homeassistant_url
  auth_providers:
  - type: homeassistant
  customize:
    zone.home:
      beacon:
        uuid: !secret home_ibeacon
        major: 0
        minor: 0

person:

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 1000
    icon: mdi:briefcase

mqtt:
  broker: home.humby.co.za
  port: 1883
  discovery: true
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

sensor:
  # Power meter sensor
  - platform: mqtt
    unique_id: "powermeter.power_remain_kwh"
    name: "Power remaining"
    state_topic: "powermeter"
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.power_remain_kwh | round(1) }}"
    expire_after: 600
    device_class: energy
  - platform: mqtt
    unique_id: "powermeter.power_watts.avg_1min"
    name: "Power usage"
    state_topic: "powermeter"
    unit_of_measurement: "W"
    value_template: "{{ value_json.power_watts.avg_1min }}"
    expire_after: 600
    device_class: energy

  # Eskom loadshedding
  - platform: mqtt
    unique_id: "loadshedding.stage"
    name: "Loadshedding stage"
    state_topic: "loadshedding/stage"
    value_template: "{{ value | int }}"
    expire_after: 1800
    device_class: energy

  # Luftdaten Particulate
  - platform: rest
    name: Air Sensor
    resource: http://10.0.0.11/data.json
    method: GET
    value_template: '{{ value_json.age }}'
    json_attributes: sensordatavalues
  - platform: template
    sensors:
      air_quality_pm10:
        friendly_name: 'PM10'
        unit_of_measurement: 'µg/m³'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'SDS_P1' %}
                  {{ i.value }}
              {% endif %}
          {% endfor %}
      air_quality_pm25:
        friendly_name: 'PM2.5'
        unit_of_measurement: 'µg/m³'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'SDS_P2' %}
                  {{ i.value }}
              {% endif %}
          {% endfor %}
      indoor_temp:
        friendly_name: 'Indoor Temperature'
        device_class: temperature
        unit_of_measurement: '°C'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'temperature' %}
                  {{ i.value | round(1) }}
              {% endif %}
          {% endfor %}
      indoor_humidity:
        friendly_name: 'Indoor Humidity'
        device_class: humidity
        unit_of_measurement: '%'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'humidity' %}
                  {{ i.value | round(0) }}
              {% endif %}
          {% endfor %}

  # Google Maps travel time
  - platform: google_travel_time
    api_key: !secret google_maps_api_key
    name: Work by car
    origin: zone.home
    destination: zone.work
    options:
      mode: driving
    scan_interval: 1800  # Only update travel time every 30 min outside of commute time

frontend:

mobile_app:

google_assistant:
  project_id: !secret google_project_id
  service_account: !include HASSGoogAssist.json
  report_state: true
  exposed_domains:
    - switch
    - light

homekit:

apple_tv:

tts:
  - platform: google_translate

updater:
  include_used_components: true

system_health:

history:

owntracks:

sun:

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml

group: !include groups.yaml
light: !include lights.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml
