# Load default config
#default_config:

homeassistant:
  name: Home
  time_zone: Africa/Johannesburg
  unit_system: metric
  temperature_unit: C
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 0
  internal_url: "http://10.0.0.10:8123"
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 10.0.0.0/24

frontend:

mobile_app:

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 200
    icon: mdi:home
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 1000
    icon: mdi:briefcase

mqtt:
  broker: 10.0.0.10
  port: 1883
  discovery: true
  client_id: homeassistant

sensor:
  # Power meter sensor
  - platform: mqtt
    unique_id: "powermeter.power_remain_kwh"
    name: "Power remaining"
    state_topic: "powermeter"
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.power_remain_kwh | round(1) }}"
    expire_after: 600
    device_class: energy
  - platform: mqtt
    unique_id: "powermeter.power_watts.avg_1min"
    name: "Power usage"
    state_topic: "powermeter"
    unit_of_measurement: "W"
    value_template: "{{ value_json.power_watts.avg_1min }}"
    expire_after: 600
    device_class: energy

  # Luftdaten Particulate
  - platform: rest
    name: Air Sensor
    resource: http://10.0.0.125/data.json
    method: GET
    value_template: '{{ value_json.age }}'
    json_attributes: sensordatavalues
  - platform: template
    sensors:
      air_quality_pm10:
        friendly_name: 'PM10'
        unit_of_measurement: 'µg/m³'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'SDS_P1' %}
                  {{ i.value }}
              {% endif %}
          {% endfor %}
      air_quality_pm25:
        friendly_name: 'PM2.5'
        unit_of_measurement: 'µg/m³'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'SDS_P2' %}
                  {{ i.value }}
              {% endif %}
          {% endfor %}
      indoor_temp:
        friendly_name: 'Indoor Temperature'
        device_class: temperature
        unit_of_measurement: '°C'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'temperature' %}
                  {{ i.value | round(1) }}
              {% endif %}
          {% endfor %}
      indoor_humidity:
        friendly_name: 'Indoor Humidity'
        device_class: humidity
        unit_of_measurement: '%'
        value_template: >-
          {% for i in states.sensor.air_sensor.attributes.sensordatavalues %}
              {% if i.value_type == 'humidity' %}
                  {{ i.value | round(0) }}
              {% endif %}
          {% endfor %}

  # Google Maps travel time
  - platform: google_travel_time
    api_key: !secret google_maps_api_key
    name: Work by car
    origin: zone.home
    destination: zone.work
    options:
      mode: driving

tts:
  - platform: google_translate

updater:
  include_used_components: true

system_health:

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml

#group: !include groups.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml
