- platform: group
  name: Hall lights
  entities:
    - light.entrance_overhead
    - light.hall_overhead

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_overhead
    - light.bedside_lights
    - light.bedroom_floor

- platform: group
  name: Study lights
  entities:
    - light.study_overhead
    - light.study_bedside_lamp

- platform: group
  name: Bathroom lights
  entities:
    - light.bathroom_overhead
    - light.bathroom_cabinet

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_overhead
    - light.kitchen_counter
    - light.kitchen_window
    - light.diningroom_overhead

- platform: group
  name: Lounge lights
  entities:
    - light.lounge_tree
    - light.lounge_overhead
    - light.lounge_window
    - light.lounge_dale_desk

- platform: switch
  name: Lounge candles
  entity_id: switch.lounge_candles

- platform: switch
  name: Bathroom cabinet
  entity_id: switch.bathroom_switch_left
