- platform: switch
  name: Bedside Light
  entity_id: switch.bedside_light

- platform: switch
  name: Shelf Light
  entity_id: switch.shelf_light

- platform: switch
  name: Desk Light
  entity_id: switch.desk_light

- platform: switch
  name: Study Light
  entity_id: switch.study_light

- platform: group
  name: Dining room lights
  entities:
    - light.diningbulb1
    - light.diningbulb2

- platform: group
  name: Lounge lights
  entities:
    - light.loungebulb1
    - light.loungebulb2
    - light.loungebulb3

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchenbulb1
    - light.kitchenbulb2
    - light.kitchenbulb3

- platform: group
  name: Bedroom overhead lights
  entities:
    - light.bedroombulb1
    - light.bedroombulb2
    - light.bedroombulb3

- platform: group
  name: Study overhead lights
  entities:
    - light.studybulb1
    - light.studybulb2
    - light.studybulb3
