- platform: group
  name: Hall lights
  entities:
    - light.entrance_overhead
    - light.foyer_overhead

- platform: group
  name: Lounge lights
  entities:
    - light.lounge_tree
    - light.lounge_overhead

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_downlights
    - light.kitchen_desk

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_overhead
    - light.bedside_lights
    - light.bedroom_floor
