# Date and time sensor
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_utc'

# Sun rise and set times
- platform: template
  sensors:
    nextsunrise:
      unique_id: sun.sun_rise
      friendly_name: "Next Sunrise"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom("%H:%M") }}
      icon_template: mdi:weather-sunset-up
    nextsunset:
      unique_id: sun.sun_set
      friendly_name: "Next Sunset"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom("%H:%M") }}
      icon_template: mdi:weather-sunset-down

- platform: filter
  name: "Solar radiation average"
  entity_id: "sensor.wunderground_solar_radiation"
  filters:
    - filter: time_simple_moving_average
      window_size: "00:10"

