# For most things template.yaml should be used. 
#
# This is mostly used for statistics (or less often, filter) functions
# https://www.home-assistant.io/integrations/statistics/

- platform: statistics
  name: Solar radiation average
  entity_id: sensor.wunderground_solar_radiation
  state_characteristic: mean
  max_age:
    minutes: 10
  keep_last_sample: true
  precision: 0

- platform: statistics
  name: Kitchen illuminance average
  entity_id: sensor.kitchen_ceiling_pir_illuminance_lux
  state_characteristic: mean
  max_age:
    minutes: 5
  keep_last_sample: true
  precision: 0
