# This is for using the "sensor" platorm.
# Most things should use the Template platform (template.yaml)
#
# This is mostly used for statistics (or less often, filter) functions
# https://www.home-assistant.io/integrations/statistics/

- platform: statistics
  name: Solar radiation average
  entity_id: sensor.wunderground_solar_radiation
  state_characteristic: mean
  max_age:
    minutes: 10
  keep_last_sample: true
  precision: 0

- platform: statistics
  name: Kitchen illuminance average
  entity_id: sensor.kitchen_ceiling_pir_illuminance
  state_characteristic: mean
  max_age:
    minutes: 5
  keep_last_sample: true
  precision: 0

- platform: min_max
  name: Average temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.bedroom_air_temperature
    - sensor.lounge_air_temperature
    - sensor.study_air_temperature

- platform: min_max
  name: Average humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.bedroom_air_humidity
    - sensor.lounge_air_humidity
    - sensor.study_air_humidity
