# For most things template.yaml should be used. 
#
# This is mostly used for statistics (or less often, filter) functions
# https://www.home-assistant.io/integrations/statistics/

- platform: statistics
  name: Solar radiation average
  entity_id: sensor.wunderground_solar_radiation
  state_characteristic: average_linear
  max_age:
    minutes: 10
  precision: 0

- platform: statistics
  name: Kitchen illuminance average
  entity_id: sensor.test_pir_illuminance_lux
  state_characteristic: average_linear
  max_age:
    minutes: 2
  precision: 0
